Mis/Mis/Models/FindDoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mis.Models
{
    public class FindDoctorViewModel
    {
        public String FirstName { get; set; }

        public String LastName { get; set; }

        public String Position { get; set; }

        public String HospitalName { get; set; }

        public List<DoctorInfo> Doctors { get; set; }
    }
}

Mis/Mis/Controllers/FindDoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Mis.Data;
using Mis.Models;

namespace Mis.Controllers
{
    public class FindDoctorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FindDoctorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var doctors = _context
                .DoctorInfo
                .Include(info => info.Hospital)
                .Include(info => info.User)
                .ToList();
            var model = new FindDoctorViewModel() { Doctors = doctors };
            return View(model);
        }

        public IActionResult Find(FindDoctorViewModel model)
        {
            model.Doctors = _context
                .DoctorInfo
                .Include(info => info.Hospital)
                .Include(info => info.User)
                .Where(info => (String.IsNullOrEmpty(model.Position) || info.Position.Contains(model.Position)) &&
                               (String.IsNullOrEmpty(model.HospitalName) || info.Hospital.Name.Contains(model.HospitalName)) && 
                               (String.IsNullOrEmpty(model.FirstName) || info.User.FirstName.Contains(model.FirstName)) &&
                               (String.IsNullOrEmpty(model.LastName) || info.User.LastName.Contains(model.LastName)))
                .ToList();
            return View("Index", model);
        }
    }
}

Mis/Mis/Views/FindDoctor/Index.cshtml
@using Mis.Models
@model FindDoctorViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-info">
    <h2>Find a Doctor</h2>
</div>

<form asp-controller="FindDoctor" asp-action="Find" method="get">
    <div>
        <hr/>
        <div class="row">
            <div class="col-md-3">
                <div class="block-info">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group">
                                <label>First name</label>
                                <input asp-for="@Model.FirstName" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Last name</label>
                                <input asp-for="@Model.LastName" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Hospital name</label>
                                <input asp-for="@Model.HospitalName" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Position</label>
                                <input asp-for="@Model.Position" class="form-control">
                            </div>
                            <div asp-validation-summary="All" class="text-danger"></div>
                        </div>
                        <div class="card-footer">
                            <input type="submit" value="Update" class="btn btn-primary" style="width: auto"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                @foreach (var doctor in Model.Doctors)
                {
                    await Html.RenderPartialAsync("~/Views/Partial/DoctorItem.cshtml", doctor);
                }
            </div>
        </div>
    </div>
</form>