Mis/Mis/Models/FindHospitalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mis.Models
{
    public class FindHospitalViewModel
    {
        public String Name { get; set; }

        public String Address { get; set; }

        public List<Hospital> Hospitals { get; set; }
    }
}

Mis/Mis/Controllers/FindHospitalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Mis.Data;
using Mis.Models;

namespace Mis.Controllers
{
    public class FindHospitalController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FindHospitalController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var hospitals = _context.Hospital.ToList();
            var model = new FindHospitalViewModel() { Hospitals = hospitals };
            return View(model);
        }

        public IActionResult Find(FindHospitalViewModel model)
        {
            model.Hospitals = _context
                .Hospital
                .Where(hospital => (String.IsNullOrEmpty(model.Name) || hospital.Name.Contains(model.Name)) &&
                               (String.IsNullOrEmpty(model.Address) || hospital.Address.Contains(model.Address)))
                .ToList();
            return View("Index", model);
        }
    }
}

Mis/Mis/Views/FindHospital/Index.cshtml
@using Mis.Models
@model FindHospitalViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-info">
    <h2>Find a Hospital</h2>
</div>

<form asp-controller="FindHospital" asp-action="Find" method="get">
    <div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <div class="block-info">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group">
                                <label>Hospital name</label>
                                <input asp-for="@Model.Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Address</label>
                                <input asp-for="@Model.Address" class="form-control">
                            </div>
                            <div asp-validation-summary="All" class="text-danger"></div>
                        </div>
                        <div class="card-footer">
                            <input type="submit" value="Update" class="btn btn-primary" style="width: auto" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                @foreach(var hospital in Model.Hospitals)
                {
                    await Html.RenderPartialAsync("~/Views/Partial/HospitalItem.cshtml", hospital);
                }
            </div>
        </div>
    </div>
</form>