Mis/Mis/Controllers/HospitalManagerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Mis.Data;
using Mis.Models;

namespace Mis.Controllers
{
    public class HospitalManagerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HospitalManagerController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hospital.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddHospital()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHospital(Hospital hospital)
        {
            if(hospital != null)
            {
                hospital.Id = Guid.NewGuid().ToString();
                _context.Hospital.Add(hospital);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ManageHospital(string hospitalId)
        {
            return View(_context.Hospital.Find(hospitalId));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult ManageHospital(Hospital hospital)
        {
            if(hospital != null)
            {
                _context.Hospital.Update(hospital);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Mis/Mis/Views/HospitalManager/AddHospital.cshtml
@model Hospital
@{
    ViewData["Title"] = "AddHospital";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Add New Hospital</h2>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input asp-for="@Model.Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input asp-for="@Model.Address" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea asp-for="@Model.Description" class="form-control"></textarea>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Update" class="btn btn-primary" style="width: auto"/>
                    <a asp-action="Index" class="btn btn-primary" style="width: auto">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</form>

Mis/Mis/Views/HospitalManager/Index.cshtml
@model List<Hospital>
@{
    ViewData["Title"] = "Hospital Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Hospital Manager</h1>

<a class="btn btn-primary" asp-controller="HospitalManager" asp-action="AddHospital" >Add New Hospital</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var hospital in Model)
        {
            <tr>
                <td>@hospital.Id</td>
                <td>@hospital.Name</td>
                <td>@hospital.Address</td>
                <td>
                    <a class="btn btn-primary" asp-controller="HospitalProfile" asp-action="Index" asp-route-hospitalId="@hospital.Id">Hospital Profile</a>
                </td>
                <td>
                    <a class="btn btn-primary" asp-controller="HospitalManager" asp-action="ManageHospital" asp-route-hospitalId="@hospital.Id">Manage Hospital</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Mis/Mis/Views/HospitalManager/ManageHospital.cshtml
@model Hospital
@{
    ViewData["Title"] = "ManageHospital";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Manage Hospital</h2>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input asp-for="@Model.Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Address</label>
                        <input asp-for="@Model.Address" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea asp-for="@Model.Description" class="form-control"></textarea>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Update" class="btn btn-primary" style="width: auto" />
                    <a asp-action="Index" class="btn btn-primary" style="width: auto">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</form>